#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
source "$PROJECT_ROOT/setup_env.sh"
# Micro-ROS Agent wrapper script
# Generated by 003_apply_config.sh

export HOME=/home/khadas
export ROS_DOMAIN_ID=0
export ROS_NAMESPACE=drone1
export RMW_IMPLEMENTATION=rmw_fastrtps_cpp

# ROS2 환경 로드
source /opt/ros/humble/setup.bash

# 워크스페이스 로드
if [ -f $PROJECT_ROOT/micro_ros_ws/install/setup.bash ]; then
    source $PROJECT_ROOT/micro_ros_ws/install/setup.bash
fi

if [ -f $PROJECT_ROOT/px4_ros2_ws/install/setup.bash ]; then
    source $PROJECT_ROOT/px4_ros2_ws/install/setup.bash
fi

# 라이브러리 경로
export LD_LIBRARY_PATH=$PROJECT_ROOT/micro_ros_ws/install/micro_ros_agent/lib:/opt/ros/humble/lib:/opt/ros/humble/lib/aarch64-linux-gnu:${LD_LIBRARY_PATH}

# micro-ROS Agent 실행
exec $PROJECT_ROOT/micro_ros_ws/install/micro_ros_agent/lib/micro_ros_agent/micro_ros_agent udp4 --port 8888
