#!/bin/bash
# Micro-ROS Agent wrapper script
# Generated by 003_apply_config.sh

# 프로젝트 환경 변수 로드
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
source "$PROJECT_ROOT/setup_env.sh"

export HOME=/home/khadas
export ROS_DOMAIN_ID=
export ROS_NAMESPACE=
export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
# DDS 프로파일 자동 선택 (SITL/FC 모드)
# - FC 모드: loopback만 사용 → eth0 멀티캐스트가 FC 이더넷에 부하주는 것 방지
# - SITL 모드: eth0+loopback 사용 → eth0에 FC 없으므로 부하 문제 없음, DDS 정상 통신
MAVLINK_CONF="/etc/mavlink-router/main.conf"
if [ -f "$MAVLINK_CONF" ] && grep -q '\[UdpEndpoint SITL\]\|\[UdpEndpoint PC_SITL\]' "$MAVLINK_CONF"; then
    export FASTRTPS_DEFAULT_PROFILES_FILE="$PROJECT_ROOT/config/fastdds_agent_eth0.xml"
    DDS_MODE="eth0+loopback (SITL)"
else
    export FASTRTPS_DEFAULT_PROFILES_FILE="$PROJECT_ROOT/config/fastdds_loopback_only.xml"
    DDS_MODE="loopback only (FC 부하 방지)"
fi

# ROS2 환경 로드
source /opt/ros/humble/setup.bash

# 워크스페이스 로드 (환경 변수 사용)
if [ -f "$MICRO_ROS_WS/install/setup.bash" ]; then
    source "$MICRO_ROS_WS/install/setup.bash"
fi

if [ -f "$PX4_ROS2_WS/install/setup.bash" ]; then
    source "$PX4_ROS2_WS/install/setup.bash"
fi

# 라이브러리 경로
if [ -d "$MICRO_ROS_WS/install/micro_ros_agent/lib" ]; then
    export LD_LIBRARY_PATH="$MICRO_ROS_WS/install/micro_ros_agent/lib:/opt/ros/humble/lib:/opt/ros/humble/lib/aarch64-linux-gnu:${LD_LIBRARY_PATH}"
fi

# DDS 프로파일 최종 확정 (exec 직전 — .bashrc 등의 환경변수 오염 방지)
MAVLINK_CONF="/etc/mavlink-router/main.conf"
if [ -f "$MAVLINK_CONF" ] && grep -q '\[UdpEndpoint SITL\]\|\[UdpEndpoint PC_SITL\]' "$MAVLINK_CONF"; then
    FINAL_DDS_PROFILE="$PROJECT_ROOT/config/fastdds_agent_eth0.xml"
else
    FINAL_DDS_PROFILE="$PROJECT_ROOT/config/fastdds_loopback_only.xml"
fi
echo "  FastDDS Profile (final): $FINAL_DDS_PROFILE"

# micro-ROS Agent 실행 (SCHED_FIFO는 systemd ExecStartPost에서 root 권한으로 적용)
if [ -f "$MICRO_ROS_WS/install/micro_ros_agent/lib/micro_ros_agent/micro_ros_agent" ]; then
    unset FASTRTPS_DEFAULT_PROFILES_FILE
    export FASTRTPS_DEFAULT_PROFILES_FILE="$FINAL_DDS_PROFILE"
    exec "$MICRO_ROS_WS/install/micro_ros_agent/lib/micro_ros_agent/micro_ros_agent" udp4 --port 8888
else
    echo "Error: micro_ros_agent not found at $MICRO_ROS_WS/install/micro_ros_agent/lib/micro_ros_agent/micro_ros_agent"
    exit 1
fi
