#!/bin/bash
# Micro-ROS Agent wrapper script
# Generated by 003_apply_config.sh

# 프로젝트 환경 변수 로드
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
source "$PROJECT_ROOT/setup_env.sh"

export HOME=/home/khadas
export ROS_DOMAIN_ID=0
# ROS_NAMESPACE는 PX4 uXRCE-DDS와 호환성 문제가 있을 수 있으므로 제거
# PX4 uXRCE-DDS는 기본적으로 네임스페이스를 사용하지 않음
# export ROS_NAMESPACE=drone3
export RMW_IMPLEMENTATION=rmw_fastrtps_cpp

# FastDDS가 eth0(10.0.0.x)만 사용하도록 설정 (WiFi 인터페이스 제외)
# 이렇게 하면 다른 VIM4 보드와 WiFi를 통한 DDS discovery가 방지됨
export FASTRTPS_DEFAULT_PROFILES_FILE="$PROJECT_ROOT/config/fastdds_eth0_only.xml"

# ROS2 환경 로드
source /opt/ros/humble/setup.bash

# 워크스페이스 로드 (환경 변수 사용)
if [ -f "$MICRO_ROS_WS/install/setup.bash" ]; then
    source "$MICRO_ROS_WS/install/setup.bash"
fi

if [ -f "$PX4_ROS2_WS/install/setup.bash" ]; then
    source "$PX4_ROS2_WS/install/setup.bash"
fi

# 라이브러리 경로
if [ -d "$MICRO_ROS_WS/install/micro_ros_agent/lib" ]; then
    export LD_LIBRARY_PATH="$MICRO_ROS_WS/install/micro_ros_agent/lib:/opt/ros/humble/lib:/opt/ros/humble/lib/aarch64-linux-gnu:${LD_LIBRARY_PATH}"
fi

# micro-ROS Agent 실행
if [ -f "$MICRO_ROS_WS/install/micro_ros_agent/lib/micro_ros_agent/micro_ros_agent" ]; then
    exec "$MICRO_ROS_WS/install/micro_ros_agent/lib/micro_ros_agent/micro_ros_agent" udp4 --port 8888
else
    echo "Error: micro_ros_agent not found at $MICRO_ROS_WS/install/micro_ros_agent/lib/micro_ros_agent/micro_ros_agent"
    exit 1
fi
